apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-volume
  namespace: data-processing
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "34.84.139.83"
    path: "/exports"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-data-volume
  namespace: data-processing
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi