swagger: "2.0"
info:
  description: "User API Sercure Endpoints"
  version: 1.0.0
  title: User API
host: "users.endpoints.PROJECT_ID.cloud.goog"
x-google-endpoints:
  - name: "users.endpoints.PROJECT_ID.cloud.goog"
basePath: /users/v1
tags:
  - name: users
    description: User API
consumes:
- "application/json"
- "text/html"
produces:
- "application/json"
- "text/html"
schemes:
- "http"
paths:
  "/roles":
    get:
      description: "roles list api"
      operationId: "roles"
      produces:
      - "text/html"
      responses:
        200:
          description: "Success"
          schema:
            type: array

securityDefinitions:
  # This section configures authentication using Google API Service Accounts
  # to sign a json web token. This is mostly used for server-to-server
  # communication.
  service-accout:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # This must match the 'iss' field in the JWT.
    x-google-issuer: "service_account_001@PROJECT_ID.iam.gserviceaccount.com"
    # Update this with your service account's email address.
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/service_account_001@PROJECT_ID.iam.gserviceaccount.com"

security:
  - service-accout: []