apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sample-app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app-container
        image: asia.gcr.io/project-abc123/sample-app:latest
        ports:
          - containerPort: 8080
        # environment variables for the Job
        env:
        - name: PROJECT_ID
          value: "project-abc123"
        - name: CONTAINER_REGISTRY_REPO
          value: "asia.gcr.io"
        - name: STATUS_UPDATE_ENDPOINT
          value: "http://UPDATE_TO_YOUR_IP/updatejobstatus"
